## Pandas - Importing data

Please download the following data and move it to an appropriate folder:

- <a href="https://drive.google.com/file/d/1gVDDJg3Ngnz8h9f2pX9AcdgWgx5zkV6U/view?usp=sharing">Bridge Inspections excerpt</a>.

In [1]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

In [2]:
## import data and store in dataframe call dfbi (short perhaps for dataframe bridge inspections)
dfbi = pd.read_csv("bridge-inspections-excerpt.csv")

In [4]:
## call the first 10 rows
dfbi.head(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN
7,47,189,'GOOSE CREEK',36033059.0,86040120.0,2.0,8.0,1965.0,2,19.0,N,N,N,6,6,NaN
8,47,189,'BRANCH',36014830.0,86030353.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,6,NaN
9,47,189,'PURTLE CREEK',36004548.0,86023480.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,6,NaN

In [5]:
## call the last 5 rows
dfbi.tail(5)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [6]:
## call a 20 random rows
dfbi.sample(20)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
35493,48,491,'RANGER BRANCH',30403511.0,97364637.0,1.0,7.0,1964.0,1,19.0,N,N,N,7,7,NaN
10959,48,485,'DEER CREEK',33521520.0,98463778.0,1.0,8.0,1961.0,1,19.0,N,N,N,6,6,NaN
83702,51,165,'LONG GLADE CREEK',38221339.0,79000912.0,1.0,6.0,1980.0,1,19.0,N,N,N,7,7,NaN
69283,48,141,'HONDO PASS DR',31520964.0,106262656.0,NaN,19.0,1980.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
20510,48,401,'PARKER CREEK',32055668.0,94515392.0,1.0,2.0,1950.0,1,19.0,N,N,N,5,6,NaN
79913,51,61,'Crooked Run',38554745.0,77555484.0,1.0,6.0,1957.0,5,1.0,6,6,7,7,N,NaN
44789,48,85,'WATTERS CREEK',33065563.0,96412391.0,4.0,19.0,2007.0,5,5.0,7,7,6,6,N,1.0
89594,51,163,'SPRING GAP CREEK',37374310.0,79354161.0,1.0,9.0,2010.0,5,1.0,7,7,7,6,N,NaN
22920,48,39,'BRAZOS RIVER',29084052.0,95362470.0,1.0,6.0,2007.0,4,2.0,7,7,6,6,N,NaN
18943,48,293,'WATSON BR #223',31325465.0,96450838.0,2.0,9.0,2009.0,3,2.0,6,7,7,7,N,NaN
68035,48,113,'Miller Ferry Rd & UP RR',32362039.0,96413958.0,NaN,17.0,2014.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
87015,51,87,'GILLIES CREEK',37313108.0,77203294.0,2.0,17.0,1991.0,1,19.0,N,N,N,6,6,NaN
14870,48,451,'DRAINAGE DITCH',31210284.0,100114142.0,1.0,2.0,1994.0,1,19.0,N,N,N,7,7,NaN
91390,51,37,'Rts 15 & 360 Bypass',37021069.0,78281425.0,NaN,2.0,1965.0,4,2.0,NaN,NaN,NaN,NaN,NaN,NaN
19764,48,1,'MOUND PRAIRIE CREEK',31521874.0,95363460.0,1.0,7.0,1965.0,1,19.0,N,N,N,6,6,NaN
5320,48,379,'Hauak Creek',32541185.0,95440464.0,2.0,9.0,1995.0,3,2.0,6,6,5,5,N,NaN
68833,48,61,'SPUR 54',26114337.0,97431135.0,NaN,14.0,1971.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
52364,48,199,'LOWER ROCKY CREEK',30125394.0,94170142.0,1.0,7.0,1979.0,1,19.0,N,N,N,7,6,NaN
20355,48,213,'WALNUT CREEK',32091780.0,95584737.0,1.0,8.0,1992.0,1,2.0,7,7,7,6,N,NaN
9347,48,439,'TRIB CLR FRK TRINITY RIV',32403170.0,97243619.0,4.0,16.0,1985.0,1,19.0,N,N,N,7,6,NaN

In [16]:
## get basic overview of the data
## what datatypes do the different columns hold?: float64(7), int64(3), str(6)
## how many rows and columns are there: 100000 rows, 16 columns
dfbi.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   STATE_CODE_001           100000 non-null  int64
 1   COUNTY_CODE_003          100000 non-null  int64
 2   FEATURES_DESC_006A       100000 non-null  str
 3   LAT_016                  99493 non-null   float64
 4   LONG_017                 99486 non-null   float64
 5   OWNER_022                82621 non-null   float64
 6   FUNCTIONAL_CLASS_026     99660 non-null   float64
 7   YEAR_BUILT_027           99997 non-null   float64
 8   STRUCTURE_KIND_043A      100000 non-null  int64
 9   STRUCTURE_TYPE_043B      99999 non-null   float64
 10  DECK_COND_058            82621 non-null   str
 11  SUPERSTRUCTURE_COND_059  82621 non-null   str
 12  SUBSTRUCTURE_COND_060    82621 non-null   str
 13  CHANNEL_COND_061         82621 non-null   str
 14  CULVERT_COND_062         82621 non-null   str
 15  PIER_PROTECTION_111      4353 non-null    float64
dtypes: float64(7), int64(3), str(6)
memory usage: 12.2 MB

### Which column has the most missing data...just a quick estimate?

In [18]:
## The column with the most missing data would be the "PIER_PROTECTION_111" column becasue it has the smalled non-null (data containing) count.

In [19]:
## call the top 7 rows
dfbi.head(7)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
0,47,189,'BRANCH',35595580.0,86115051.0,2.0,8.0,1965.0,2,19.0,N,N,N,7,5,NaN
1,47,189,'BRANCH',35575281.0,86103402.0,2.0,8.0,1930.0,2,19.0,N,N,N,7,7,NaN
2,47,189,'BRANCH',36062250.0,86245507.0,2.0,8.0,1935.0,2,19.0,N,N,N,7,5,NaN
3,47,189,'OVERFLOW',36060931.0,86245689.0,2.0,8.0,1960.0,2,19.0,N,N,N,7,7,NaN
4,47,189,'HURRICANE CREEK',36031626.0,86251979.0,2.0,8.0,1970.0,3,2.0,6,5,5,8,N,NaN
5,47,189,'PURTLE CREEK',36000534.0,86024153.0,2.0,8.0,1995.0,2,19.0,N,N,N,8,6,NaN
6,47,189,'GOOSE CREEK',36035202.0,86033583.0,2.0,8.0,1960.0,2,4.0,7,6,6,6,N,NaN

In [20]:
## call a sample of 10
dfbi.sample(10)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
12485,48,303,'DRAINAGE DITCH',33364922.0,101483399.0,1.0,12.0,1974.0,1,19.0,N,N,N,6,6,NaN
63888,48,201,'SH 288 TL',29383692.0,95231404.0,NaN,19.0,2020.0,5,2.0,NaN,NaN,NaN,NaN,NaN,NaN
38681,48,29,'APACHE CREEK',29244755.0,98314361.0,4.0,14.0,1972.0,2,1.0,7,7,7,7,N,NaN
11,47,189,'DRY FORK CREEK',36100846.0,86073431.0,2.0,8.0,1928.0,2,19.0,N,N,N,7,5,NaN
83092,51,153,'POWELLS CREEK',38362262.0,77183390.0,1.0,11.0,1963.0,3,2.0,7,6,5,7,N,NaN
18078,48,145,'LITTLE BRAZOS RIVER',31191470.0,96412547.0,2.0,9.0,2017.0,3,2.0,7,7,7,6,N,NaN
22070,48,347,'BOGGY CREEK TRIBUTARY',31221450.0,94203393.0,2.0,9.0,1960.0,1,19.0,N,N,N,5,7,NaN
31903,48,481,'COLORADO RIVER RELIEF',29171011.0,96072566.0,1.0,7.0,1933.0,1,19.0,N,N,N,7,6,NaN
40258,48,25,'POESTA CREEK & T-AROUNDS',28233542.0,97432711.0,1.0,14.0,1973.0,5,2.0,7,8,7,7,N,NaN
81119,51,87,'JORDANS CREEK',37350200.0,77295700.0,2.0,19.0,1960.0,5,1.0,6,6,5,6,N,NaN

In [21]:
## call the bottom 6
dfbi.tail(6)

,STATE_CODE_001,COUNTY_CODE_003,FEATURES_DESC_006A,LAT_016,LONG_017,OWNER_022,FUNCTIONAL_CLASS_026,YEAR_BUILT_027,STRUCTURE_KIND_043A,STRUCTURE_TYPE_043B,DECK_COND_058,SUPERSTRUCTURE_COND_059,SUBSTRUCTURE_COND_060,CHANNEL_COND_061,CULVERT_COND_062,PIER_PROTECTION_111
99994,53,61,'SWAMP CREEK',47482979.0,122152176.0,2.0,16.0,1963.0,1,22.0,7,7,5,6,N,NaN
99995,53,39,'TROUT CREEK',45595604.0,121314080.0,2.0,7.0,1956.0,2,1.0,6,6,5,8,N,NaN
99996,53,65,'COLVILLE RIVER',48103246.0,117434719.0,2.0,7.0,1960.0,3,2.0,5,6,6,8,N,NaN
99997,53,77,'DRAIN',46195400.0,120161800.0,2.0,9.0,1965.0,7,2.0,7,4,4,8,N,NaN
99998,53,53,'LEACH CREEK',47122326.0,122305265.0,4.0,14.0,1981.0,3,19.0,N,N,N,8,7,NaN
99999,53,75,'SOUTH FORK PALOUSE RIVER',46461734.0,117141254.0,2.0,9.0,1963.0,5,4.0,5,6,7,7,N,NaN

In [22]:
## call the year built column using dot notation
dfbi.YEAR_BUILT_027

0        1965.0
1        1930.0
2        1935.0
3        1960.0
4        1970.0
          ...
99995    1956.0
99996    1960.0
99997    1965.0
99998    1981.0
99999    1963.0
Name: YEAR_BUILT_027, Length: 100000, dtype: float64

In [23]:
## call FEATURES_DESC_006A as a series using square bracket notation
dfbi["FEATURES_DESC_006A"]

0                          'BRANCH'
1                          'BRANCH'
2                          'BRANCH'
3                        'OVERFLOW'
4                 'HURRICANE CREEK'
                    ...
99995                 'TROUT CREEK'
99996              'COLVILLE RIVER'
99997                       'DRAIN'
99998                 'LEACH CREEK'
99999    'SOUTH FORK PALOUSE RIVER'
Name: FEATURES_DESC_006A, Length: 100000, dtype: str

In [17]:
## what are the unique owner codes?
dfbi.OWNER_022.unique()

array([ 2.,  4.,  1.,  3., 79., 63., 67., 64., 70., 66., 72., 74., nan,
       68., 21., 80., 31., 32., 11., 40., 25., 26., 75., 12., 27., 55.,
       56., 69., 62., 73., 76., 54., 77.])

### What do these codes mean?

In [ ]:
## These codes refer to each different owner ID, showing us how many unique IDs there are and what they are.